# See https://docs.giantswarm.io/reference/platform-api/chart-metadata/
# for details and background.

apiVersion: v2
name: grafana-organization
description: Giant Swarm Observability Platform GrafanaOrganization CR.
home: https://github.com/giantswarm/grafana-organization-app
icon: https://s.giantswarm.io/app-icons/grafana/1/light.svg
sources:
  - https://github.com/giantswarm/grafana-organization-app
version: 0.0.1
annotations:
  io.giantswarm.application.audience: giantswarm
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: "shield"
